// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZe_IyBGd_Z316TCzXoc9u5eUNn05NvWI',
    appId: '1:637169842678:web:8a1133515bb6c8c378efd7',
    messagingSenderId: '637169842678',
    projectId: 'trackerapp-cd3b9',
    authDomain: 'trackerapp-cd3b9.firebaseapp.com',
    storageBucket: 'trackerapp-cd3b9.appspot.com',
    measurementId: 'G-NXFJXWXFJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmpGFLYJqHn07kC4WqaBUh0U1F5hium2A',
    appId: '1:637169842678:android:b77d984e953d652978efd7',
    messagingSenderId: '637169842678',
    projectId: 'trackerapp-cd3b9',
    storageBucket: 'trackerapp-cd3b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_iqPJFP0ll-eQZw9oaEqZ4679Won-G7I',
    appId: '1:637169842678:ios:46c7c247ec01bca478efd7',
    messagingSenderId: '637169842678',
    projectId: 'trackerapp-cd3b9',
    storageBucket: 'trackerapp-cd3b9.appspot.com',
    androidClientId: '637169842678-3ju7iuhpq5amkuvvpdvu6lj98q0nb8pr.apps.googleusercontent.com',
    iosClientId: '637169842678-nlu4689dgcl93dlcli1jdm0on82udts0.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_iqPJFP0ll-eQZw9oaEqZ4679Won-G7I',
    appId: '1:637169842678:ios:46c7c247ec01bca478efd7',
    messagingSenderId: '637169842678',
    projectId: 'trackerapp-cd3b9',
    storageBucket: 'trackerapp-cd3b9.appspot.com',
    androidClientId: '637169842678-3ju7iuhpq5amkuvvpdvu6lj98q0nb8pr.apps.googleusercontent.com',
    iosClientId: '637169842678-nlu4689dgcl93dlcli1jdm0on82udts0.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitApp',
  );
}
